package:
	name: SimulationIO
	version: "0.1.0"

source:
	git_rev: release-0.1
	git_url: https://github.com/eschnett/SimulationIO.git

build:
	number: 0

requirements:
	build:
	- cython
	- swig
	- gcc >= 4.8.5
	- hdf5 >= 1.8.16
	- libgcc >= 4.8.5
	- mpi4py
	- mpich
	- setuptools
run:
	- numpy
	- scipy
	- h5py
	- mpi4py
	- hdf5 >= 1.8.16
	- libgcc >= 4.8.5
	- mpich

about:
	home: https://github.com/eschnett/SimulationIO
	license: LGPLv3
